### ISSUE TITLE
[SaveToRedux] inability to save images - 

### ISSUE THREAD

**Issue by TheBladeron** [1Lighty/BetterDiscordPlugins#11]
after a while of saving images from a... particular server - images named image0, image1, image2, etc... stopped saving entirely even after full reboot of Discord, turning the plugin off and back on, and wiping the contents in my Downloads folders

**Comment by 1Lighty** [comment]
There is a limit to how many duplicate image names there can be before it just flat out refuses to work.

It will only save up to eg `image(99).png` no more. This should be roughly 100 images.

**Comment by TheBladeron** [comment]
is there a way you could increase the limit?

**Comment by 1Lighty** [comment]
Assuming it is indeed that limit you're hitting, I've increased it to 500 images, do test it out to see if it solves your issue.

[SaveToRedux.plugin.zip](https://github.com/1Lighty/BetterDiscordPlugins/files/4911322/SaveToRedux.plugin.zip)

**Comment by TheBladeron** [comment]
its working 
yay - lol -

**Comment by 1Lighty** [comment]
Should be no longer an issue as of 3442545ce68a334971d79d07dd936bb16fb57bd4.
