### ISSUE TITLE
[UnreadBadgesRedux] Badges regress back to original behavior after an unknown period of time

### ISSUE THREAD

**Issue by ramenchef** [1Lighty/BetterDiscordPlugins#14]
The badges on the server icons revert back to white dots after an unspecified period of time. Working fixes so far are to either restart the discord client or to disable and then reenable the plugin. This happens whether or not the Discord client is minimized to the systray. I have tried updating both discord and Bandaged BD, but this does not fix the issue.

OS: Windows 10 64-bit 2004
Discord: 0.0.307
BBD: 0.3.5
Injector: 0.6.2

**Comment by 1Lighty** [comment]
Not sure if this is still an issue?
