### ISSUE TITLE
MessageLoggerV2: Latest update cannot be compiled due to mismatching braces

### ISSUE THREAD

**Issue by aronson** [1Lighty/BetterDiscordPlugins#18]
Upon auto-updating to the latest version of the MessageLogger plugin, I'm presented with this error and the plugin won't load:
![image](https://user-images.githubusercontent.com/1026348/94474195-4ab70880-019b-11eb-87b1-92dfbd38fae0.png)

Seems like a routine bug, did you miss a brace? Let me know if you need any additional information

**Comment by Xetaxheb** [comment]
#17 17
