### ISSUE TITLE
1XenoLib could not be compiled

### ISSUE THREAD

**Issue by JohnWeak1** [1Lighty/BetterDiscordPlugins#22]
this happens upon loading plugins and makes other plugins un-usable 

![image](https://user-images.githubusercontent.com/42245432/95378248-ebb46a80-08e3-11eb-8756-931ead7fdab0.png)

**Comment by 1Lighty** [comment]
This was already fixed in 4c1436537fda7ee58ab38a6517555b32e2b7042b
