### ISSUE TITLE
Picture and Edits Not Showing Up

### ISSUE THREAD

**Issue by Godly-Avenger** [1Lighty/BetterDiscordPlugins#26]
I asked a friend to edit a couple messages and delete some photos. When I was using Discord, it worked, but after I left, I couldn't see any new edits or deletes. I could still see the old ones though. I set the plugin to not ignore anything. Please help.

**Comment by 1Lighty** [comment]
This is better suites in the support server and not github. https://discord.gg/NYvWdN5
