### ISSUE TITLE
[BetterImageViewer] Missing arrows

### ISSUE THREAD

**Issue by ItsRogueRen** [1Lighty/BetterDiscordPlugins#29]
BetterImageViewer seems to be missing the arrows to go through images. All the other features seem to work though, so I'm confused why that's the only thing not working. Its one of my most used plugin features so if there's any data I can send to help fix it I'd be glad to.

**Comment by 1Lighty** [comment]
May be related to a recent issue with zeres library

**Comment by 1Lighty** [comment]
This should be fixed as of 502d56118b6762ebf239c37bef8d775a7ae7f319.
