### ISSUE TITLE
[1XenoLib] 1XenoLib could not be compiled

### ISSUE THREAD

**Issue by cafeed28** [1Lighty/BetterDiscordPlugins#30]
XenoLib could not be compiled: XenoLib is not defined
![image](https://user-images.githubusercontent.com/62172116/100771627-74511200-3420-11eb-9461-57c9f99b6c20.png)

**Comment by 1Lighty** [comment]
![image](https://user-images.githubusercontent.com/49841131/100778743-ae61ea00-3407-11eb-9bff-dbaa7836c1c6.png)
