### ISSUE TITLE
[BetterImageViewer] - "Resize images to take up more space" BETA Breaks in embeds

### ISSUE THREAD

**Issue by TheHDCrafter** [1Lighty/BetterDiscordPlugins#32]
On
![DiscordCanary 12 12 2020 - 17 51 - 19](https://user-images.githubusercontent.com/29355595/101989783-11267180-3ca3-11eb-8478-5ebba7e96b94.png)
Off
![DiscordCanary 12 12 2020 - 17 51 - 33](https://user-images.githubusercontent.com/29355595/101989786-12579e80-3ca3-11eb-9add-3ada4706f63d.png)

How to reproduce: Have an image in an embed, turn on the plugin and it doesn't resize the embed to fit the image.

**Comment by 1Lighty** [comment]
This has been fixed in 587310b8ff9e034ba565beba7983e10e6b6d120d.
Simply update to 1.5.2.
