### ISSUE TITLE
[BetterImageViewer] View avatar/View icon option

### ISSUE THREAD

**Issue by Dschogo** [1Lighty/BetterDiscordPlugins#33]
Hey Awesome stuff :D

Would like to see an option to view avatars/ servericons without needing to save them with Savetoredux. (Like Imageutilities from Devilbro) 
would be cool to be able to see the "search on google" feature.

**Comment by 1Lighty** [comment]
This feature has nothing to do with the theme of BetterImageViewer and is best served as another plugin.
https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/AvatarIconViewer.plugin.js
