### ISSUE TITLE
[MessageLoggerV2] Deleted videos not shown in logger

### ISSUE THREAD

**Issue by Itzdlg** [1Lighty/BetterDiscordPlugins#35]
When a user deletes a video, the video appears to have a red "deleted" tint. However, when I navigate to the user's deleted messages logs, the white text saying it's not broken is not there. There is also no video, even though it was clearly deleted.

**Comment by 1Lighty** [comment]
Sadly this is a limitation of how the menu was made. The video is also not locally saved so even if it was displayed properly, it wouldn't play.
