### ISSUE TITLE
[SaveToRedux] Trying to Save an Images Result in a "Unknown Error: 401"

### ISSUE THREAD

**Issue by Ryonez** [1Lighty/BetterDiscordPlugins#36]
As the titles states basically.

Worked initially bar another issue, before returning only this error.

**Comment by 1Lighty** [comment]
401, authorization issue. Whatever image you were trying to save may have been deleted.

**Comment by Ryonez** [comment]
They are shouldn't be. I can see them, open them in the browser and save them manually.

**Comment by Ryonez** [comment]
An now it seems to be working and I can't find an image it was having issue with. When I created this issue, It was having issues with any image I tried to save. So not sure what to do now I can't replicate it anymore.
