### ISSUE TITLE
Implement full resolution image previews or fix incompatibility with BetterImagePopups

### ISSUE THREAD

**Issue by briank6932** [1Lighty/BetterDiscordPlugins#4]
The plugin [BetterImagePopups](https://github.com/Orrielel/BetterDiscordAddons/tree/master/Plugins/BetterImagePopups) allows for full resolution image previews, however this bugs out zooming functionality with BetterImageViewer.

**Comment by 1Lighty** [comment]
I will be implementing the full res preview soon, even if I really am just unable to tell the difference between downscaled and fullres.

**Comment by 1Lighty** [comment]
Since BetterImagePopups is of poor quality and I have way better ways of doing it, I implemented the feature in 3db9fb9569363f5880f93fb22f7be873870bda1d.
But from my own testing, it doesn't make any difference so not sure why you'd want it.
